#!/bin/sh
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 daizu-coder
#
# Generates pico/pico_int_offs.h for the CE (cegcc/arm-mingw32ce) build.
#
# Not a general-purpose replacement for tools/mkoffsets.sh: only emits the
# subset of OFS_* macros pico/draw_arm.S and pico/draw2_arm.S actually
# reference (verified via grep). tools/mkoffsets.sh itself can't be reused
# as-is against this
# toolchain: (1) its cross-prefix detection does
# `echo $CC | sed 's/gcc.*//'`, which truncates at the *first* "gcc"
# substring anywhere in the path - and "/opt/cegcc/bin/arm-mingw32ce-gcc"
# has one inside "cegcc" itself, so it computes a bogus prefix and silently
# falls back to the host's objdump; (2) even with that fixed, it greps the
# compiled test object for a `.rodata`/`.sdata` section, but this
# toolchain's PE/COFF output names it `.rdata` (confirmed via
# arm-mingw32ce-objdump -h), so the section is never found. Both were
# confirmed by hand before writing this script - see the dev notes.
#
# usage: CC=<cross-gcc> CFLAGS=<...> sh ./mkoffsets_ce.sh <output-dir>

set -e
CC=${CC:-arm-mingw32ce-gcc}
OBJDUMP=${OBJDUMP:-arm-mingw32ce-objdump}
fn="${1:-.}/pico_int_offs.h"

get_define () {
	# $1=macro name  $2=struct type  $3=field expression
	struct=$2; field=$3
	cat > /tmp/mkoffs_ce.c <<EOF
#include <stdint.h>
#include <pico/pico_int.h>
static struct $struct p;
const int32_t val = (char *)&p.$field - (char *)&p;
EOF
	$CC $CFLAGS -c /tmp/mkoffs_ce.c -o /tmp/mkoffs_ce.o
	# the constant is the sole word in .rdata; read it back byte-swapped
	# (LE target) via objdump -s, same technique as upstream mkoffsets.sh
	hexle=$($OBJDUMP -s -j .rdata /tmp/mkoffs_ce.o | awk '/^ 0/{print $2; exit}')
	b0=$(echo $hexle | cut -c1-2); b1=$(echo $hexle | cut -c3-4)
	b2=$(echo $hexle | cut -c5-6); b3=$(echo $hexle | cut -c7-8)
	val=$(printf "%d" 0x$b3$b2$b1$b0)
	printf "#define %-20s 0x%04x\n" "$1" "$val"
}

echo "/* generated by tools/mkoffsets_ce.sh for the CE build, do not edit */" >$fn
echo "/* see tools/mkoffsets_ce.sh for why tools/mkoffsets.sh doesn't work here */" >>$fn
get_define OFS_Pico_video_reg    Pico       video.reg     >>$fn
get_define OFS_Pico_m_dirtyPal   Pico       m.dirtyPal    >>$fn
get_define OFS_Pico_m_hardware   Pico       m.hardware    >>$fn
get_define OFS_EST_DrawScanline  PicoEState DrawScanline  >>$fn
get_define OFS_EST_rendstatus    PicoEState rendstatus    >>$fn
get_define OFS_EST_DrawLineDest  PicoEState DrawLineDest  >>$fn
get_define OFS_EST_HighCol       PicoEState HighCol       >>$fn
get_define OFS_EST_HighPreSpr    PicoEState HighPreSpr    >>$fn
get_define OFS_EST_Pico          PicoEState Pico          >>$fn
get_define OFS_EST_PicoMem_vram  PicoEState PicoMem_vram  >>$fn
get_define OFS_EST_PicoMem_cram  PicoEState PicoMem_cram  >>$fn
get_define OFS_EST_PicoOpt       PicoEState PicoOpt       >>$fn
get_define OFS_EST_HighPal       PicoEState HighPal       >>$fn
get_define OFS_EST_Draw2FB       PicoEState Draw2FB       >>$fn
get_define OFS_EST_Draw2Start    PicoEState Draw2Start    >>$fn
get_define OFS_PMEM_vram         PicoMem    vram          >>$fn
get_define OFS_PMEM_vsram        PicoMem    vsram         >>$fn
get_define OFS_PicoIn_opt        PicoInterface opt        >>$fn
get_define OFS_PicoIn_filter     PicoInterface filter     >>$fn
get_define OFS_PicoIn_AHW        PicoInterface AHW        >>$fn

echo "generated $fn:"
cat $fn
